service: ms-auth
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
 
functions:
  verification:
    name: verification-lambda
    handler: src/verification.verification
    timeout: 5
    memorySize: 128
    events:
      - httpApi:
          path: /ms-auth/verification-user
          method: post
