
name: Deploy Aws Lambda with serverless 

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install NPM dependencies
        run: npm install
      - name: Serverless AWS authentication
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create env file
        run: | # create env.yml
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Deploy Lambda functions
        run: sls deploy --stage dev --region ${{ secrets.AWS_REGION }}
